[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow = "1"
toml_edit = "0.22"
clap = { version = "4.5", features = ["derive"] }

[lints]
workspace = true
