[package]
name = "succinct-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
sp1-sdk = "4.2.0"
witness-generator.workspace = true
metrics.workspace = true
dotenv = "0.15.0"

[lints]
workspace = true
