[package]
name = "ere-hosts"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
benchmark-runner.workspace = true
ere-sp1.workspace = true
ere-risczero.workspace = true
ere-pico.workspace = true
zkvm-interface.workspace = true

[lints]
workspace = true
