name: Rust Checks
on:
  push:
    branches: [ main, master, jsign-ci-cache ]
  pull_request:
    branches: [ main, master ]

env:
  CARGO_TERM_COLOR: always

jobs: 
  check:
    name: Minimal checks on non-zkvm crates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
      
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: base 

      - name: Check formatting
        run: cargo fmt --check --all

      - name: Run tests
        run: cargo test -p zkevm-metrics -p witness-generator -p ere-hosts

  download-eest-fixtures:
    name: Download and Extract Fixtures
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download and Extract Fixtures
        run: |
          chmod +x ./scripts/download-and-extract-fixtures.sh
          ./scripts/download-and-extract-fixtures.sh

  check-ere-host:
    name: Checks crate ere-hosts
    strategy:
      fail-fast: false
      matrix:
        zkvm: [sp1, risc0, openvm, pico, zisk]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.zkvm }}

      - name: Cargo check (with ${{ matrix.zkvm }} enabled)
        run: cargo check --features ${{ matrix.zkvm }} -p ere-hosts
