name: Rust Checks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Minimal checks on non-zkvm crates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download and Extract Fixtures
        run: |
          chmod +x ./scripts/download-and-extract-fixtures.sh
          ./scripts/download-and-extract-fixtures.sh

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Check formatting
        run: cargo fmt --check --all

      - name: Run tests
        run: cargo test -p metrics -p witness-generator