name: Stateless Executor Benchmark
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:
  schedule:
    # Run every day at 2 AM UTC
    - cron: '0 2 * * *'

env:
  CARGO_TERM_COLOR: always

jobs: 
  stateless-executor:
    name: Stateless Executor Benchmark
    runs-on: [self-hosted-ghr, size-xl-x64]
    strategy:
      fail-fast: false
      matrix:
        zkvm: [sp1, risc0]
        action: [execute, prove]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
      
      - name: Download and Extract Fixtures
        run: |
          chmod +x ./scripts/download-and-extract-fixtures.sh
          ./scripts/download-and-extract-fixtures.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install C toolchain dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang libclang-dev
      
      - name: Generate benchmark fixtures
        run: RUST_LOG=info cargo run -p witness-generator-cli --release -- tests --include 1M- --include Prague --include empty_block

      - name: Run stateless-executor benchmark
        run: RUST_LOG=info cargo run -p ere-hosts --release --features ${{ matrix.zkvm }} -- --action ${{ matrix.action }} stateless-executor
      
      - name: Check zkevm-metrics folder
        run: |
          find ./zkevm-metrics
          if [ ! -d "./zkevm-metrics" ]; then
            echo "zkevm-metrics folder does not exist"
            exit 1
          fi
          if [ ! -f "./zkevm-metrics/hardware.json" ]; then
            echo "hardware.json file does not exist in zkevm-metrics folder"
            exit 1
          fi
          zkvm_folder=$(find ./zkevm-metrics -type d -name "${{ matrix.zkvm }}-*" | head -n 1)
          if [ -z "$zkvm_folder" ]; then
            echo "No ${{ matrix.zkvm }} folder found in zkevm-metrics"
            exit 1
          fi
          ls -l ./zkevm-fixtures-input
          ls -l $zkvm_folder
          input_files_count=$(find ./zkevm-fixtures-input -type f | wc -l)
          zkvm_files_count=$(find $zkvm_folder -type f | wc -l)
          if [ "$input_files_count" -ne "$zkvm_files_count" ]; then
            echo "Mismatch in number of files: zkevm-fixtures-input has $input_files_count files, $zkvm_folder has $zkvm_files_count files"
            exit 1
          fi

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: stateless-executor-${{ matrix.zkvm }}-${{ matrix.action }}-${{ github.run_id }}
          path: zkevm-metrics/
          retention-days: 30

      - name: Generate benchmark report
        if: always()
        run: |
          echo "## Stateless Executor Benchmark Results" >> $GITHUB_STEP_SUMMARY
          echo "**zkVM:** ${{ matrix.zkvm }}" >> $GITHUB_STEP_SUMMARY
          echo "**Action:** ${{ matrix.action }}" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ -d "./zkevm-metrics" ]; then
            zkvm_folder=$(find ./zkevm-metrics -type d -name "${{ matrix.zkvm }}-*" | head -n 1)
            if [ -n "$zkvm_folder" ]; then
              echo "**Results folder:** $zkvm_folder" >> $GITHUB_STEP_SUMMARY
              echo "**Files generated:** $(find $zkvm_folder -type f | wc -l)" >> $GITHUB_STEP_SUMMARY
            fi
          fi 